### ISSUE TITLE
No logs sent, due to error on $logQuery in CLAW-Aggregator.ps1

### ISSUE THREAD

**Issue by dnnadmins** [Azure/trusted-internet-connection#2]
v.1.16
There appears to be an error on lines 122, and 123.  You set the $logQuery = "search * | distinct Type | sort by Type asc"  which overwrites your incoming variable on the function (normally the query for the log data itself) and ends up in an empty logset each time.

Changing $logQuery on those lines to use $logQuery2 (or some alternate variable name) fixes the problem and allows the proper logQuery to be set on line 139 "$results = Invoke-AzOperationalInsightsQuery -WorkspaceId $LogAnalyticWorkspaceID -Query $logQuery"

**Comment by paullizer** [comment]
Good catch! I've renamed value to $logQueryType.

I appreciate taking the time to share the issue and provide a correction! Have a great day Rob!
